/**
 * NameToColor Brazilian Portuguese language pack.
 *
 * Load this file after NameToColor.js. It contains data only; all language
 * handling logic remains in the English core library. Color-name keys use
 * six hexadecimal digits without a leading "#".
 */
registerNameToColorLanguage({
    locale: 'pt-BR',
    name: 'Português (Brasil)',

    inputAliases: {
        random: ['aleatório', 'aleatória', 'ao acaso'],
        transparent: ['transparente'],
        dark: ['escuro', 'escura'],
        darker: ['mais escuro', 'mais escura'],
        light: ['claro', 'clara'],
        lighter: ['mais claro', 'mais clara'],
        bright: ['brilhante', 'vivo', 'viva'],
        brighter: ['mais brilhante', 'mais vivo', 'mais viva']
    },

    moodNames: {
        Vibrant: 'Vibrante',
        Futuristic: 'Futurista',
        Fun: 'Divertido',
        'Soft Pastel': 'Pastel Suave',
        Calm: 'Calmo',
        Vintage: 'Retrô',
        Organic: 'Orgânico',
        Sophisticated: 'Sofisticado',
        Dark: 'Escuro',
        Corporate: 'Corporativo'
    },

    themeAliases: {
        Vibrant: ['vibrante', 'vivo', 'energético', 'intenso'],
        Futuristic: ['futurista', 'futuro', 'cibernético', 'ficção científica', 'néon'],
        Fun: ['divertido', 'alegre', 'brincalhão', 'lúdico'],
        'Soft Pastel': ['pastel suave', 'tons pastel', 'delicado', 'suave'],
        Calm: ['calmo', 'tranquilo', 'sereno', 'relaxante'],
        Vintage: ['retrô', 'nostálgico', 'antigo', 'clássico'],
        Organic: ['orgânico', 'natural', 'artesanal', 'terroso'],
        Sophisticated: ['sofisticado', 'elegante', 'refinado', 'requintado'],
        Dark: ['escuro', 'sombrio', 'noturno', 'pouca luz'],
        Corporate: ['corporativo', 'empresarial', 'profissional', 'escritório'],

        Nature: ['natureza', 'ar livre', 'vida selvagem', 'ecologia', 'mundo natural'],
        Forest: ['floresta', 'bosque', 'mata', 'selva', 'floresta verde'],
        Water: ['água', 'aquático', 'água doce', 'rio', 'lago', 'chuva'],
        Ocean: ['oceano', 'mar', 'marinho', 'náutico', 'alto mar'],
        Beach: ['praia', 'costa', 'litoral', 'beira-mar', 'areia da praia'],
        Mountain: ['montanha', 'alpino', 'cume', 'trilha', 'serra'],
        Desert: ['deserto', 'árido', 'dunas', 'tempestade de areia', 'sertão'],
        Tropical: ['tropical', 'trópicos', 'floresta tropical', 'ilha', 'paraíso tropical'],
        Floral: ['floral', 'flor', 'flores', 'botânico', 'buquê'],
        Earth: ['terra', 'solo', 'argila', 'terracota', 'tons terrosos'],
        Sky: ['céu', 'nuvens', 'luz do dia', 'céu azul', 'ar aberto'],
        Sunset: ['pôr do sol', 'entardecer', 'crepúsculo', 'hora dourada', 'anoitecer'],
        Night: ['noite', 'meia-noite', 'luar', 'noturno', 'céu noturno'],
        Space: ['espaço', 'cosmos', 'galáxia', 'universo', 'astronomia'],
        Spring: ['primavera', 'estação das flores', 'florescer', 'primaveril'],
        Summer: ['verão', 'ensolarado', 'sol', 'estação quente'],
        Autumn: ['outono', 'colheita', 'folhagem', 'folhas secas'],
        Winter: ['inverno', 'neve', 'gelo', 'geada', 'estação fria'],

        Metal: ['metal', 'metálico', 'liga metálica', 'cromado', 'metal polido'],
        Gold: ['ouro', 'dourado', 'folheado a ouro', 'ouro metálico'],
        Silver: ['prata', 'prateado', 'prata de lei', 'metal prateado'],
        Copper: ['cobre', 'bronze', 'latão', 'acobreado'],
        Wood: ['madeira', 'amadeirado', 'tábua', 'madeira maciça', 'veios da madeira'],
        Stone: ['pedra', 'rocha', 'mármore', 'granito', 'ardósia'],
        Concrete: ['concreto', 'cimento', 'alvenaria', 'concreto aparente'],
        Glass: ['vidro', 'cristal', 'vidro transparente', 'vidro fosco'],

        Children: ['crianças', 'criança', 'infantil', 'menino', 'menina'],
        Baby: ['bebê', 'bebês', 'recém-nascido', 'berçário', 'maternidade'],
        Youth: ['juventude', 'jovem', 'adolescente', 'público jovem', 'geração z'],
        Wedding: ['casamento', 'noiva', 'nupcial', 'cerimônia de casamento'],
        Romance: ['romance', 'romântico', 'amor', 'dia dos namorados', 'paixão'],
        Celebration: ['celebração', 'festa', 'festivo', 'aniversário', 'festival'],
        Wellness: ['bem-estar', 'spa', 'meditação', 'ioga', 'autocuidado'],
        Luxury: ['luxo', 'luxuoso', 'exclusivo', 'alto padrão', 'prestígio'],

        Coffee: ['café', 'cafeteria', 'expresso', 'cappuccino', 'barista'],
        Food: ['comida', 'alimentação', 'culinária', 'cozinha', 'alimentos'],
        Restaurant: ['restaurante', 'refeição', 'bistrô', 'lanchonete', 'gastronomia'],
        Agriculture: ['agricultura', 'fazenda', 'cultivo', 'agrícola', 'agronegócio'],
        Industry: ['indústria', 'industrial', 'fábrica', 'manufatura', 'produção'],
        Construction: ['construção', 'construtora', 'arquitetura', 'infraestrutura', 'engenharia civil'],
        Automotive: ['automotivo', 'carro', 'veículo', 'motor', 'corrida'],
        Technology: ['tecnologia', 'tecnológico', 'digital', 'software', 'inovação'],
        Gaming: ['jogos', 'jogo', 'jogador', 'esportes eletrônicos', 'videogame'],
        Healthcare: ['saúde', 'médico', 'hospital', 'clínica', 'medicina'],
        Finance: ['finanças', 'financeiro', 'banco', 'bancário', 'investimento'],
        Education: ['educação', 'escola', 'aprendizado', 'acadêmico', 'universidade'],
        Science: ['ciência', 'científico', 'laboratório', 'pesquisa', 'química'],
        Energy: ['energia', 'elétrico', 'eletricidade', 'potência', 'energia solar'],
        Sustainability: ['sustentabilidade', 'sustentável', 'renovável', 'energia verde', 'ecológico'],
        'Real Estate': ['imóveis', 'imobiliário', 'propriedade', 'moradia', 'corretor de imóveis'],
        Travel: ['viagem', 'turismo', 'férias', 'jornada', 'destino'],
        Sports: ['esportes', 'esporte', 'fitness', 'atlético', 'competição'],
        Music: ['música', 'áudio', 'som', 'concerto', 'banda'],
        Fashion: ['moda', 'roupa', 'vestuário', 'alta-costura', 'guarda-roupa'],
        Retail: ['varejo', 'compras', 'loja', 'comércio', 'comércio eletrônico'],
        Security: ['segurança', 'proteção', 'cibersegurança', 'seguro', 'defesa'],
        Beauty: ['beleza', 'cosméticos', 'maquiagem', 'cuidados com a pele', 'salão'],
        Pets: ['animais de estimação', 'pet', 'cachorro', 'gato', 'veterinário'],
        Minimal: ['minimalista', 'design limpo', 'simples', 'design neutro', 'essencial']
    },

    colorNames: {
        '000000': ['Preto'],
        'c0c0c0': ['Prata'],
        '808080': ['Cinza'],
        'ffffff': ['Branco'],
        '800000': ['Bordô'],
        'ff0000': ['Vermelho'],
        '800080': ['Roxo', 'Púrpura'],
        'ff00ff': ['Magenta', 'Fúcsia'],
        '008000': ['Verde'],
        '00ff00': ['Lima', 'Verde-limão puro'],
        '808000': ['Oliva'],
        'ffff00': ['Amarelo'],
        '000080': ['Azul-marinho'],
        '0000ff': ['Azul'],
        '008080': ['Verde-azulado', 'Petróleo'],
        '00ffff': ['Ciano', 'Água'],
        'f0f8ff': ['Azul Alice'],
        'faebd7': ['Branco antigo'],
        '7fffd4': ['Água-marinha'],
        'f0ffff': ['Azul-celeste'],
        'f5f5dc': ['Bege'],
        'ffe4c4': ['Bisque'],
        'ffebcd': ['Amêndoa clara'],
        '8a2be2': ['Azul-violeta'],
        'a52a2a': ['Marrom'],
        'deb887': ['Madeira clara'],
        '5f9ea0': ['Azul-cadete'],
        '7fff00': ['Chartreuse'],
        'd2691e': ['Chocolate'],
        'ff7f50': ['Coral'],
        '6495ed': ['Azul-centáurea'],
        'fff8dc': ['Seda de milho'],
        'dc143c': ['Carmesim'],
        '00008b': ['Azul escuro'],
        '008b8b': ['Ciano escuro'],
        'b8860b': ['Dourado escuro'],
        'a9a9a9': ['Cinza escuro'],
        '006400': ['Verde escuro'],
        'bdb76b': ['Cáqui escuro'],
        '8b008b': ['Magenta escuro'],
        '556b2f': ['Verde-oliva escuro'],
        'ff8c00': ['Laranja escuro'],
        '9932cc': ['Orquídea escura'],
        '8b0000': ['Vermelho escuro'],
        'e9967a': ['Salmão escuro'],
        '8fbc8f': ['Verde-mar escuro'],
        '483d8b': ['Azul-ardósia escuro'],
        '2f4f4f': ['Cinza-ardósia escuro'],
        '00ced1': ['Turquesa escuro'],
        '9400d3': ['Violeta escuro'],
        'ff1493': ['Rosa profundo'],
        '00bfff': ['Azul-céu profundo'],
        '696969': ['Cinza fosco'],
        '1e90ff': ['Azul vívido'],
        'b22222': ['Tijolo'],
        'fffaf0': ['Branco floral'],
        '228b22': ['Verde floresta'],
        'dcdcdc': ['Gainsboro'],
        'f8f8ff': ['Branco fantasma'],
        'ffd700': ['Dourado'],
        'daa520': ['Ocre dourado'],
        'adff2f': ['Verde-amarelo claro'],
        'f0fff0': ['Orvalho'],
        'ff69b4': ['Rosa choque'],
        'cd5c5c': ['Vermelho indiano'],
        '4b0082': ['Índigo'],
        'fffff0': ['Marfim'],
        'f0e68c': ['Cáqui'],
        'e6e6fa': ['Lavanda'],
        'fff0f5': ['Rubor lavanda'],
        '7cfc00': ['Verde gramado'],
        'fffacd': ['Creme de limão'],
        'add8e6': ['Azul claro'],
        'f08080': ['Coral claro'],
        'e0ffff': ['Ciano claro'],
        'fafad2': ['Amarelo dourado claro'],
        'd3d3d3': ['Cinza claro'],
        '90ee90': ['Verde claro'],
        'ffb6c1': ['Rosa claro'],
        'ffa07a': ['Salmão claro'],
        '20b2aa': ['Verde-mar claro'],
        '87cefa': ['Azul-céu claro'],
        '778899': ['Cinza-ardósia claro'],
        'b0c4de': ['Azul-aço claro'],
        'ffffe0': ['Amarelo claro'],
        '32cd32': ['Verde-limão'],
        'faf0e6': ['Linho'],
        '66cdaa': ['Água-marinha média'],
        '0000cd': ['Azul médio'],
        'ba55d3': ['Orquídea média'],
        '9370db': ['Roxo médio'],
        '3cb371': ['Verde-mar médio'],
        '7b68ee': ['Azul-ardósia médio'],
        '00fa9a': ['Verde-primavera médio'],
        '48d1cc': ['Turquesa médio'],
        'c71585': ['Vermelho-violeta médio'],
        '191970': ['Azul meia-noite'],
        'f5fffa': ['Creme de menta'],
        'ffe4e1': ['Rosa névoa'],
        'ffe4b5': ['Mocassim'],
        'ffdead': ['Branco navajo'],
        'fdf5e6': ['Renda antiga'],
        '6b8e23': ['Oliva opaca'],
        'ffa500': ['Laranja'],
        'ff4500': ['Vermelho-alaranjado'],
        'da70d6': ['Orquídea'],
        'eee8aa': ['Dourado pálido'],
        '98fb98': ['Verde pálido'],
        'afeeee': ['Turquesa pálido'],
        'db7093': ['Vermelho-violeta pálido'],
        'ffefd5': ['Creme de papaia'],
        'ffdab9': ['Pêssego'],
        'cd853f': ['Peru'],
        'ffc0cb': ['Rosa'],
        'dda0dd': ['Ameixa'],
        'b0e0e6': ['Azul-pó'],
        '663399': ['Roxo Rebecca'],
        'bc8f8f': ['Marrom rosado'],
        '4169e1': ['Azul royal'],
        '8b4513': ['Marrom sela'],
        'fa8072': ['Salmão'],
        'f4a460': ['Marrom areia'],
        '2e8b57': ['Verde-mar'],
        'fff5ee': ['Concha'],
        'a0522d': ['Siena'],
        '87ceeb': ['Azul-céu'],
        '6a5acd': ['Azul-ardósia'],
        '708090': ['Cinza-ardósia'],
        'fffafa': ['Neve'],
        '00ff7f': ['Verde-primavera'],
        '4682b4': ['Azul-aço'],
        'd2b48c': ['Bronzeado'],
        'd8bfd8': ['Cardo'],
        'ff6347': ['Tomate'],
        '40e0d0': ['Turquesa'],
        'ee82ee': ['Violeta'],
        'f5deb3': ['Trigo'],
        'f5f5f5': ['Fumaça branca'],
        '9acd32': ['Verde-amarelado']
    }
});
